//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mökkivarausjärjestelmä_1._0.Tietokanta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mokki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mokki()
        {
            this.Varaus = new HashSet<Varaus>();
        }
    
        public int Idmokki { get; set; }
        public string mokkinimi { get; set; }
        public string katuosoite { get; set; }
        public string kuvaus { get; set; }
        public Nullable<int> henkilomaara { get; set; }
        public string varustelu { get; set; }
        public int ToimintaalueIdtoimintaalue { get; set; }
        public int PostiIdposti { get; set; }
    
        public virtual Toimintaalue Toimintaalue { get; set; }
        public virtual Posti Posti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Varaus> Varaus { get; set; }
    }
}
