//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mökkivarausjärjestelmä_1._0.Tietokanta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palvelu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Palvelu()
        {
            this.varauksen_palvelut = new HashSet<varauksen_palvelut>();
        }
    
        public int Idpalvelu { get; set; }
        public string nimi { get; set; }
        public Nullable<int> tyyppi { get; set; }
        public string kuvaus { get; set; }
        public Nullable<decimal> hinta { get; set; }
        public Nullable<decimal> alv { get; set; }
        public int ToimintaalueIdtoimintaalue { get; set; }
    
        public virtual Toimintaalue Toimintaalue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<varauksen_palvelut> varauksen_palvelut { get; set; }
    }
}
