//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mökkivarausjärjestelmä_1._0.Tietokanta
{
    using System;
    using System.Collections.Generic;
    
    public partial class varauksen_palvelut
    {
        public int varaus_idvaraus { get; set; }
        public Nullable<int> lkm { get; set; }
        public int PalveluIdpalvelu { get; set; }
        public int VarausIdvaraus { get; set; }
    
        public virtual Palvelu Palvelu { get; set; }
        public virtual Varaus Varaus { get; set; }
    }
}
