//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mökkivarausjärjestelmä_1._0.Tietokanta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varaus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Varaus()
        {
            this.varauksen_palvelut = new HashSet<varauksen_palvelut>();
            this.Lasku = new HashSet<Lasku>();
        }
    
        public int Idvaraus { get; set; }
        public Nullable<System.DateTime> varattu_pvm { get; set; }
        public Nullable<System.DateTime> vahvistus_pvm { get; set; }
        public Nullable<System.DateTime> varattu_alkupvm { get; set; }
        public Nullable<System.DateTime> varattu_loppupvm { get; set; }
        public int MokkiIdmokki { get; set; }
        public int AsiakasIdasiakas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<varauksen_palvelut> varauksen_palvelut { get; set; }
        public virtual Mokki Mokki { get; set; }
        public virtual Asiakas Asiakas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lasku> Lasku { get; set; }
    }
}
