//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mökkivarausjärjestelmä_1._0.Tietokanta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VillageNewbiesEntities : DbContext
    {
        public VillageNewbiesEntities()
            : base("name=VillageNewbiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakas> Asiakas { get; set; }
        public virtual DbSet<Lasku> Lasku { get; set; }
        public virtual DbSet<Mokki> Mokki { get; set; }
        public virtual DbSet<Palvelu> Palvelu { get; set; }
        public virtual DbSet<Posti> Posti { get; set; }
        public virtual DbSet<Toimintaalue> Toimintaalue { get; set; }
        public virtual DbSet<Varaus> Varaus { get; set; }
        public virtual DbSet<varauksen_palvelut> varauksen_palvelut { get; set; }
    }
}
